<?php
 return [
	 ''=>[
		 'controller'=>'main',
		 'action'=>'index',
	 ],
	 'main/login'=>[
		 'controller'=>'main',
		 'action'=>'login',
	 ],
	 'main/logout'=>[
		 'controller'=>'main',
		 'action'=>'logout',
	 ],
	 'main/organization'=>[
		 'controller'=>'main',
		 'action'=>'organization',
	 ],
	
	 'admin/worker/view'=>[
		 'controller'=>'admin',
		 'action'=>'workerView',
	 ],
	 'admin/organization'=>[
		 'controller'=>'admin',
		 'action'=>'organization',
	 ],
	 'admin/organization/view'=>[
		 'controller'=>'admin',
		 'action'=>'view',
	 ],
	 'worker/information'=>[
		 'controller'=>'worker',
		 'action'=>'information',
	 ],
	 'admin/organization/delete'=>[
		 'controller'=>'admin',
		 'action'=>'delete',
	 ],
 ];