<?php
 return [
	 ''=>[
		 'controller'=>'main',
		 'action'=>'index',
	 ],
	 'main/login'=>[
		 'controller'=>'main',
		 'action'=>'login',
	 ],
	 'main/logout'=>[
		 'controller'=>'main',
		 'action'=>'logout',
	 ],
	 'admin/worker'=>[
		 'controller'=>'admin',
		 'action'=>'worker',
	 ],
	 'admin/organization'=>[
		 'controller'=>'admin',
		 'action'=>'organization',
	 ],
	 'main/organization'=>[
		 'controller'=>'main',
		 'action'=>'organization',
	 ],
	 
	 'worker/information'=>[
		 'controller'=>'worker',
		 'action'=>'information',
	 ],
 ];