<?php
 return [
	 ''=>[
		 'controller'=>'main',
		 'action'=>'index',
	 ],
 	'account/login'=>[
 		'controller'=>'account',
        'action'=>'login',
    ],
	 'main/index'=>[
		 'controller'=>'main',
		 'action'=>'test',
	 ],
	'news/show'=>[
		'controller'=>'news',
		'action'=>'show'
	 ]
 ];